---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: terrywang/archlinux

suites:
  - name: default
    run_list:
      - recipe[chef-client::default]
      - recipe[home_infra::default]
      - recipe[home_infra::check_tv_script]
    attributes:
